version: '2'
services:
  app:
    build: ./container/tensorflow
    container_name: tm2_app
    volumes:
      - ./notebooks:/notebooks
      - ./data:/data
      - ./scripts:/var/scripts
    ports:
      - 8888:8888